# Generated by Django 4.2.14 on 2024-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
